use schemars::JsonSchema;
/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs. You should never hard code secrets or store them in plain text. Use the [Secrets API](https://docs.databricks.com/dev-tools/api/latest/secrets.html) to manage secrets in the [Databricks CLI](https://docs.databricks.com/dev-tools/cli/index.html). Use the [Secrets utility](https://docs.databricks.com/dev-tools/databricks-utils.html#dbutils-secrets) to reference secrets in notebooks and jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterCloudProviderNodeInfo {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<crate::models::ClusterCloudProviderNodeStatus>,
    /// Available CPU core quota.
    #[serde(rename = "available_core_quota", skip_serializing_if = "Option::is_none")]
    pub available_core_quota: Option<i32>,
    /// Total CPU core quota.
    #[serde(rename = "total_core_quota", skip_serializing_if = "Option::is_none")]
    pub total_core_quota: Option<i32>,
}

impl ClusterCloudProviderNodeInfo {
    pub fn new() -> ClusterCloudProviderNodeInfo {
        ClusterCloudProviderNodeInfo {
            status: None,
            available_core_quota: None,
            total_core_quota: None,
        }
    }
}


