use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BillingWrappedBudgetWithStatus {
    #[serde(rename = "budget")]
    pub budget: Box<crate::models::BillingBudgetWithStatus>,
}

impl BillingWrappedBudgetWithStatus {
    pub fn new(budget: crate::models::BillingBudgetWithStatus) -> BillingWrappedBudgetWithStatus {
        BillingWrappedBudgetWithStatus {
            budget: Box::new(budget),
        }
    }
}


