use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CatalogCreateMetastore {
    /// The user-specified name of the metastore.
    #[serde(rename = "name")]
    pub name: String,
    /// Cloud region which the metastore serves (Eg., `us-west-2`, `westus`). If this field is omitted, the region of the workspace receiving the request will be used.
    #[serde(rename = "region", skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    /// The storage root URL for metastore
    #[serde(rename = "storage_root")]
    pub storage_root: String,
}

impl CatalogCreateMetastore {
    pub fn new(name: String, storage_root: String) -> CatalogCreateMetastore {
        CatalogCreateMetastore {
            name,
            region: None,
            storage_root,
        }
    }
}


