use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CatalogPermissionsChange {
    #[serde(rename = "add", skip_serializing_if = "Option::is_none")]
    pub add: Option<Vec<crate::models::CatalogPrivilege>>,
    /// The principal whose privileges we are changing.
    #[serde(rename = "principal", skip_serializing_if = "Option::is_none")]
    pub principal: Option<String>,
    #[serde(rename = "remove", skip_serializing_if = "Option::is_none")]
    pub remove: Option<Vec<crate::models::CatalogPrivilege>>,
}

impl CatalogPermissionsChange {
    pub fn new() -> CatalogPermissionsChange {
        CatalogPermissionsChange {
            add: None,
            principal: None,
            remove: None,
        }
    }
}


