use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CatalogCreateMetastoreAssignment {
    /// The name of the default catalog in the metastore.
    #[serde(rename = "default_catalog_name")]
    pub default_catalog_name: String,
    /// The unique ID of the metastore.
    #[serde(rename = "metastore_id")]
    pub metastore_id: String,
}

impl CatalogCreateMetastoreAssignment {
    pub fn new(default_catalog_name: String, metastore_id: String) -> CatalogCreateMetastoreAssignment {
        CatalogCreateMetastoreAssignment {
            default_catalog_name,
            metastore_id,
        }
    }
}


