use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CatalogTableRowFilter {
    #[serde(rename = "input_column_names")]
    pub input_column_names: Vec<String>,
    /// The full name of the row filter SQL UDF.
    #[serde(rename = "name")]
    pub name: String,
}

impl CatalogTableRowFilter {
    pub fn new(input_column_names: Vec<String>, name: String) -> CatalogTableRowFilter {
        CatalogTableRowFilter {
            input_column_names,
            name,
        }
    }
}


