use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CatalogFunctionParameterMode : The mode of the function parameter.

/// The mode of the function parameter.
#[derive(JsonSchema, Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CatalogFunctionParameterMode {
    #[serde(rename = "IN")]
    In,

}

impl ToString for CatalogFunctionParameterMode {
    fn to_string(&self) -> String {
        match self {
            Self::In => String::from("IN"),
        }
    }
}

impl Default for CatalogFunctionParameterMode {
    fn default() -> CatalogFunctionParameterMode {
        Self::In
    }
}




