use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CatalogCreateTableConstraint {
    #[serde(rename = "constraint")]
    pub constraint: Box<crate::models::CatalogTableConstraint>,
    /// The full name of the table referenced by the constraint.
    #[serde(rename = "full_name_arg")]
    pub full_name_arg: String,
}

impl CatalogCreateTableConstraint {
    pub fn new(constraint: crate::models::CatalogTableConstraint, full_name_arg: String) -> CatalogCreateTableConstraint {
        CatalogCreateTableConstraint {
            constraint: Box::new(constraint),
            full_name_arg,
        }
    }
}


