use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComputeInstancePoolGcpAttributes {
    #[serde(rename = "gcp_availability", skip_serializing_if = "Option::is_none")]
    pub gcp_availability: Option<crate::models::ComputeGcpAvailability>,
    /// If provided, each node in the instance pool will have this number of local SSDs attached. Each local SSD is 375GB in size. Refer to [GCP documentation](https://Cloudgoogle.com/compute/docs/disks/local-ssd#choose_number_local_ssds) for the supported number of local SSDs for each instance type.
    #[serde(rename = "local_ssd_count", skip_serializing_if = "Option::is_none")]
    pub local_ssd_count: Option<i32>,
}

impl ComputeInstancePoolGcpAttributes {
    pub fn new() -> ComputeInstancePoolGcpAttributes {
        ComputeInstancePoolGcpAttributes {
            gcp_availability: None,
            local_ssd_count: None,
        }
    }
}


