use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComputeAutoScale {
    /// The maximum number of workers to which the cluster can scale up when overloaded. Note that `max_workers` must be strictly greater than `min_workers`.
    #[serde(rename = "max_workers")]
    pub max_workers: i32,
    /// The minimum number of workers to which the cluster can scale down when underutilized. It is also the initial number of workers the cluster will have after creation.
    #[serde(rename = "min_workers")]
    pub min_workers: i32,
}

impl ComputeAutoScale {
    pub fn new(max_workers: i32, min_workers: i32) -> ComputeAutoScale {
        ComputeAutoScale {
            max_workers,
            min_workers,
        }
    }
}


