use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ComputeEbsVolumeType : The type of EBS volumes that will be launched with this cluster.

/// The type of EBS volumes that will be launched with this cluster.
#[derive(JsonSchema, Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ComputeEbsVolumeType {
    #[serde(rename = "GENERAL_PURPOSE_SSD")]
    GeneralPurposeSsd,
    #[serde(rename = "THROUGHPUT_OPTIMIZED_HDD")]
    ThroughputOptimizedHdd,

}

impl ToString for ComputeEbsVolumeType {
    fn to_string(&self) -> String {
        match self {
            Self::GeneralPurposeSsd => String::from("GENERAL_PURPOSE_SSD"),
            Self::ThroughputOptimizedHdd => String::from("THROUGHPUT_OPTIMIZED_HDD"),
        }
    }
}

impl Default for ComputeEbsVolumeType {
    fn default() -> ComputeEbsVolumeType {
        Self::GeneralPurposeSsd
    }
}




