use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(JsonSchema, Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ComputeLanguage {
    #[serde(rename = "python")]
    Python,
    #[serde(rename = "scala")]
    Scala,
    #[serde(rename = "sql")]
    Sql,

}

impl ToString for ComputeLanguage {
    fn to_string(&self) -> String {
        match self {
            Self::Python => String::from("python"),
            Self::Scala => String::from("scala"),
            Self::Sql => String::from("sql"),
        }
    }
}

impl Default for ComputeLanguage {
    fn default() -> ComputeLanguage {
        Self::Python
    }
}




