use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComputeListAvailableZonesResponse {
    /// The availability zone if no `zone_id` is provided in the cluster creation request.
    #[serde(rename = "default_zone", skip_serializing_if = "Option::is_none")]
    pub default_zone: Option<String>,
    #[serde(rename = "zones", skip_serializing_if = "Option::is_none")]
    pub zones: Option<Vec<String>>,
}

impl ComputeListAvailableZonesResponse {
    pub fn new() -> ComputeListAvailableZonesResponse {
        ComputeListAvailableZonesResponse {
            default_zone: None,
            zones: None,
        }
    }
}


