use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComputeDockerImage {
    #[serde(rename = "basic_auth", skip_serializing_if = "Option::is_none")]
    pub basic_auth: Option<Box<crate::models::ComputeDockerBasicAuth>>,
    /// URL of the docker image.
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl ComputeDockerImage {
    pub fn new() -> ComputeDockerImage {
        ComputeDockerImage {
            basic_auth: None,
            url: None,
        }
    }
}


