use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ComputeInstancePoolState : Current state of the instance pool.

/// Current state of the instance pool.
#[derive(JsonSchema, Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ComputeInstancePoolState {
    #[serde(rename = "ACTIVE")]
    Active,
    #[serde(rename = "STOPPED")]
    Stopped,
    #[serde(rename = "DELETED")]
    Deleted,

}

impl ToString for ComputeInstancePoolState {
    fn to_string(&self) -> String {
        match self {
            Self::Active => String::from("ACTIVE"),
            Self::Stopped => String::from("STOPPED"),
            Self::Deleted => String::from("DELETED"),
        }
    }
}

impl Default for ComputeInstancePoolState {
    fn default() -> ComputeInstancePoolState {
        Self::Active
    }
}




