use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ComputeDataSecurityMode : This describes an enum

/// This describes an enum
#[derive(JsonSchema, Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ComputeDataSecurityMode {
    #[serde(rename = "NONE")]
    None,
    #[serde(rename = "SINGLE_USER")]
    SingleUser,
    #[serde(rename = "USER_ISOLATION")]
    UserIsolation,
    #[serde(rename = "LEGACY_TABLE_ACL")]
    LegacyTableAcl,
    #[serde(rename = "LEGACY_PASSTHROUGH")]
    LegacyPassthrough,
    #[serde(rename = "LEGACY_SINGLE_USER")]
    LegacySingleUser,

}

impl ToString for ComputeDataSecurityMode {
    fn to_string(&self) -> String {
        match self {
            Self::None => String::from("NONE"),
            Self::SingleUser => String::from("SINGLE_USER"),
            Self::UserIsolation => String::from("USER_ISOLATION"),
            Self::LegacyTableAcl => String::from("LEGACY_TABLE_ACL"),
            Self::LegacyPassthrough => String::from("LEGACY_PASSTHROUGH"),
            Self::LegacySingleUser => String::from("LEGACY_SINGLE_USER"),
        }
    }
}

impl Default for ComputeDataSecurityMode {
    fn default() -> ComputeDataSecurityMode {
        Self::None
    }
}




