use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComputePolicyFamily {
    /// Policy definition document expressed in Databricks Cluster Policy Definition Language.
    #[serde(rename = "definition")]
    pub definition: String,
    /// Human-readable description of the purpose of the policy family.
    #[serde(rename = "description")]
    pub description: String,
    /// Name of the policy family.
    #[serde(rename = "name")]
    pub name: String,
    /// ID of the policy family.
    #[serde(rename = "policy_family_id")]
    pub policy_family_id: String,
}

impl ComputePolicyFamily {
    pub fn new(definition: String, description: String, name: String, policy_family_id: String) -> ComputePolicyFamily {
        ComputePolicyFamily {
            definition,
            description,
            name,
            policy_family_id,
        }
    }
}


