use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(JsonSchema, Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ComputeCloudProviderNodeStatus {
    #[serde(rename = "NotEnabledOnSubscription")]
    NotEnabledOnSubscription,
    #[serde(rename = "NotAvailableInRegion")]
    NotAvailableInRegion,

}

impl ToString for ComputeCloudProviderNodeStatus {
    fn to_string(&self) -> String {
        match self {
            Self::NotEnabledOnSubscription => String::from("NotEnabledOnSubscription"),
            Self::NotAvailableInRegion => String::from("NotAvailableInRegion"),
        }
    }
}

impl Default for ComputeCloudProviderNodeStatus {
    fn default() -> ComputeCloudProviderNodeStatus {
        Self::NotEnabledOnSubscription
    }
}




