use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DbsqlPermissionstransferOwnershipRequest {
    /// Email address for the new owner, who must exist in the workspace.
    #[serde(rename = "new_owner", skip_serializing_if = "Option::is_none")]
    pub new_owner: Option<String>,
}

impl DbsqlPermissionstransferOwnershipRequest {
    pub fn new() -> DbsqlPermissionstransferOwnershipRequest {
        DbsqlPermissionstransferOwnershipRequest {
            new_owner: None,
        }
    }
}


