use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilesCreateResponse {
    /// Handle which should subsequently be passed into the AddBlock and Close calls when writing to a file through a stream.
    #[serde(rename = "handle", skip_serializing_if = "Option::is_none")]
    pub handle: Option<i64>,
}

impl FilesCreateResponse {
    pub fn new() -> FilesCreateResponse {
        FilesCreateResponse {
            handle: None,
        }
    }
}


