use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilesReadResponse {
    /// The number of bytes read (could be less than `length` if we hit end of file). This refers to number of bytes read in unencoded version (response data is base64-encoded). 
    #[serde(rename = "bytes_read", skip_serializing_if = "Option::is_none")]
    pub bytes_read: Option<i64>,
    /// The base64-encoded contents of the file read.
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<String>,
}

impl FilesReadResponse {
    pub fn new() -> FilesReadResponse {
        FilesReadResponse {
            bytes_read: None,
            data: None,
        }
    }
}


