use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilesMove {
    /// The destination path of the file or directory. The path should be the absolute DBFS path.
    #[serde(rename = "destination_path")]
    pub destination_path: String,
    /// The source path of the file or directory. The path should be the absolute DBFS path.
    #[serde(rename = "source_path")]
    pub source_path: String,
}

impl FilesMove {
    pub fn new(destination_path: String, source_path: String) -> FilesMove {
        FilesMove {
            destination_path,
            source_path,
        }
    }
}


