use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IamGrantRule {
    #[serde(rename = "principals", skip_serializing_if = "Option::is_none")]
    pub principals: Option<Vec<String>>,
    /// Role that is assigned to the list of principals.
    #[serde(rename = "role")]
    pub role: String,
}

impl IamGrantRule {
    pub fn new(role: String) -> IamGrantRule {
        IamGrantRule {
            principals: None,
            role,
        }
    }
}


