use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IamListGroupsResponse {
    #[serde(rename = "Resources", skip_serializing_if = "Option::is_none")]
    pub resources: Option<Vec<crate::models::IamGroup>>,
    /// Total results returned in the response.
    #[serde(rename = "itemsPerPage", skip_serializing_if = "Option::is_none")]
    pub items_per_page: Option<i64>,
    /// Starting index of all the results that matched the request filters. First item is number 1.
    #[serde(rename = "startIndex", skip_serializing_if = "Option::is_none")]
    pub start_index: Option<i64>,
    /// Total results that match the request filters.
    #[serde(rename = "totalResults", skip_serializing_if = "Option::is_none")]
    pub total_results: Option<i64>,
}

impl IamListGroupsResponse {
    pub fn new() -> IamListGroupsResponse {
        IamListGroupsResponse {
            resources: None,
            items_per_page: None,
            start_index: None,
            total_results: None,
        }
    }
}


