use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobsDbtOutput {
    /// An optional map of headers to send when retrieving the artifact from the `artifacts_link`.
    #[serde(rename = "artifacts_headers", default, skip_serializing_if = "Option::is_none")]
    pub artifacts_headers: Option<::std::collections::HashMap<String, String>>,
    /// A pre-signed URL to download the (compressed) dbt artifacts. This link is valid for a limited time (30 minutes). This information is only available after the run has finished.
    #[serde(rename = "artifacts_link", skip_serializing_if = "Option::is_none")]
    pub artifacts_link: Option<String>,
}

impl JobsDbtOutput {
    pub fn new() -> JobsDbtOutput {
        JobsDbtOutput {
            artifacts_headers: None,
            artifacts_link: None,
        }
    }
}


