use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobsCancelRun {
    /// This field is required.
    #[serde(rename = "run_id")]
    pub run_id: i64,
}

impl JobsCancelRun {
    pub fn new(run_id: i64) -> JobsCancelRun {
        JobsCancelRun {
            run_id,
        }
    }
}


