use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobsResolvedNotebookTaskValues {
    #[serde(rename = "base_parameters", default, skip_serializing_if = "Option::is_none")]
    pub base_parameters: Option<::std::collections::HashMap<String, String>>,
}

impl JobsResolvedNotebookTaskValues {
    pub fn new() -> JobsResolvedNotebookTaskValues {
        JobsResolvedNotebookTaskValues {
            base_parameters: None,
        }
    }
}


