use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobsCancelAllRuns {
    /// The canonical identifier of the job to cancel all runs of. This field is required.
    #[serde(rename = "job_id")]
    pub job_id: i64,
}

impl JobsCancelAllRuns {
    pub fn new(job_id: i64) -> JobsCancelAllRuns {
        JobsCancelAllRuns {
            job_id,
        }
    }
}


