use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// JobsGitSnapshot : Read-only state of the remote repository at the time the job was run. This field is only included on job runs.



#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobsGitSnapshot {
    /// Commit that was used to execute the run. If git_branch was specified, this points to the HEAD of the branch at the time of the run; if git_tag was specified, this points to the commit the tag points to.
    #[serde(rename = "used_commit", skip_serializing_if = "Option::is_none")]
    pub used_commit: Option<String>,
}

impl JobsGitSnapshot {
    /// Read-only state of the remote repository at the time the job was run. This field is only included on job runs.
    pub fn new() -> JobsGitSnapshot {
        JobsGitSnapshot {
            used_commit: None,
        }
    }
}


