use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// JobsTriggerType : This describes an enum

/// This describes an enum
#[derive(JsonSchema, Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum JobsTriggerType {
    #[serde(rename = "PERIODIC")]
    Periodic,
    #[serde(rename = "ONE_TIME")]
    OneTime,
    #[serde(rename = "RETRY")]
    Retry,
    #[serde(rename = "RUN_JOB_TASK")]
    RunJobTask,
    #[serde(rename = "FILE_ARRIVAL")]
    FileArrival,

}

impl ToString for JobsTriggerType {
    fn to_string(&self) -> String {
        match self {
            Self::Periodic => String::from("PERIODIC"),
            Self::OneTime => String::from("ONE_TIME"),
            Self::Retry => String::from("RETRY"),
            Self::RunJobTask => String::from("RUN_JOB_TASK"),
            Self::FileArrival => String::from("FILE_ARRIVAL"),
        }
    }
}

impl Default for JobsTriggerType {
    fn default() -> JobsTriggerType {
        Self::Periodic
    }
}




