use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobsJobParameterDefinition {
    /// Default value of the parameter.
    #[serde(rename = "default")]
    pub default: String,
    /// The name of the defined parameter. May only contain alphanumeric characters, `_`, `-`, and `.`
    #[serde(rename = "name")]
    pub name: String,
}

impl JobsJobParameterDefinition {
    pub fn new(default: String, name: String) -> JobsJobParameterDefinition {
        JobsJobParameterDefinition {
            default,
            name,
        }
    }
}


