use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobsContinuous {
    /// Indicate whether the continuous execution of the job is paused or not. Defaults to UNPAUSED.
    #[serde(rename = "pause_status", skip_serializing_if = "Option::is_none")]
    pub pause_status: Option<crate::models::JobsPauseStatus>,
}

impl JobsContinuous {
    pub fn new() -> JobsContinuous {
        JobsContinuous {
            pause_status: None,
        }
    }
}


