use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobsPipelineTask {
    /// If true, a full refresh will be triggered on the delta live table.
    #[serde(rename = "full_refresh", skip_serializing_if = "Option::is_none")]
    pub full_refresh: Option<bool>,
    /// The full name of the pipeline task to execute.
    #[serde(rename = "pipeline_id", skip_serializing_if = "Option::is_none")]
    pub pipeline_id: Option<String>,
}

impl JobsPipelineTask {
    pub fn new() -> JobsPipelineTask {
        JobsPipelineTask {
            full_refresh: None,
            pipeline_id: None,
        }
    }
}


