use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobsSqlTaskQuery {
    /// The canonical identifier of the SQL query.
    #[serde(rename = "query_id")]
    pub query_id: String,
}

impl JobsSqlTaskQuery {
    pub fn new(query_id: String) -> JobsSqlTaskQuery {
        JobsSqlTaskQuery {
            query_id,
        }
    }
}


