use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// JobsJobsHealthRules : An optional set of health rules that can be defined for this job.



#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobsJobsHealthRules {
    #[serde(rename = "rules", skip_serializing_if = "Option::is_none")]
    pub rules: Option<Vec<crate::models::JobsJobsHealthRule>>,
}

impl JobsJobsHealthRules {
    /// An optional set of health rules that can be defined for this job.
    pub fn new() -> JobsJobsHealthRules {
        JobsJobsHealthRules {
            rules: None,
        }
    }
}


