use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MlDeleteRuns {
    /// The ID of the experiment containing the runs to delete.
    #[serde(rename = "experiment_id")]
    pub experiment_id: String,
    /// An optional positive integer indicating the maximum number of runs to delete. The maximum allowed value for max_runs is 10000. 
    #[serde(rename = "max_runs", skip_serializing_if = "Option::is_none")]
    pub max_runs: Option<i32>,
    /// The maximum creation timestamp in milliseconds since the UNIX epoch for deleting runs. Only runs created prior to or at this timestamp are deleted. 
    #[serde(rename = "max_timestamp_millis")]
    pub max_timestamp_millis: i64,
}

impl MlDeleteRuns {
    pub fn new(experiment_id: String, max_timestamp_millis: i64) -> MlDeleteRuns {
        MlDeleteRuns {
            experiment_id,
            max_runs: None,
            max_timestamp_millis,
        }
    }
}


