use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MlDeleteRunsResponse {
    /// The number of runs deleted.
    #[serde(rename = "runs_deleted", skip_serializing_if = "Option::is_none")]
    pub runs_deleted: Option<i32>,
}

impl MlDeleteRunsResponse {
    pub fn new() -> MlDeleteRunsResponse {
        MlDeleteRunsResponse {
            runs_deleted: None,
        }
    }
}


