use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MlListModelsResponse {
    /// Pagination token to request next page of models for the same query.
    #[serde(rename = "next_page_token", skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
    #[serde(rename = "registered_models", skip_serializing_if = "Option::is_none")]
    pub registered_models: Option<Vec<crate::models::MlModel>>,
}

impl MlListModelsResponse {
    pub fn new() -> MlListModelsResponse {
        MlListModelsResponse {
            next_page_token: None,
            registered_models: None,
        }
    }
}


