use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MlLogModel {
    /// MLmodel file in json format.
    #[serde(rename = "model_json", skip_serializing_if = "Option::is_none")]
    pub model_json: Option<String>,
    /// ID of the run to log under
    #[serde(rename = "run_id", skip_serializing_if = "Option::is_none")]
    pub run_id: Option<String>,
}

impl MlLogModel {
    pub fn new() -> MlLogModel {
        MlLogModel {
            model_json: None,
            run_id: None,
        }
    }
}


