use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MlListArtifactsResponse {
    #[serde(rename = "files", skip_serializing_if = "Option::is_none")]
    pub files: Option<Vec<crate::models::MlFileInfo>>,
    /// Token that can be used to retrieve the next page of artifact results
    #[serde(rename = "next_page_token", skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
    /// Root artifact directory for the run.
    #[serde(rename = "root_uri", skip_serializing_if = "Option::is_none")]
    pub root_uri: Option<String>,
}

impl MlListArtifactsResponse {
    pub fn new() -> MlListArtifactsResponse {
        MlListArtifactsResponse {
            files: None,
            next_page_token: None,
            root_uri: None,
        }
    }
}


