use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MlListRegistryWebhooks {
    /// Token that can be used to retrieve the next page of artifact results
    #[serde(rename = "next_page_token", skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
    #[serde(rename = "webhooks", skip_serializing_if = "Option::is_none")]
    pub webhooks: Option<Vec<crate::models::MlRegistryWebhook>>,
}

impl MlListRegistryWebhooks {
    pub fn new() -> MlListRegistryWebhooks {
        MlListRegistryWebhooks {
            next_page_token: None,
            webhooks: None,
        }
    }
}


