use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Mlstage : This describes an enum

/// This describes an enum
#[derive(JsonSchema, Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Mlstage {
    #[serde(rename = "None")]
    None,
    #[serde(rename = "Staging")]
    Staging,
    #[serde(rename = "Production")]
    Production,
    #[serde(rename = "Archived")]
    Archived,

}

impl ToString for Mlstage {
    fn to_string(&self) -> String {
        match self {
            Self::None => String::from("None"),
            Self::Staging => String::from("Staging"),
            Self::Production => String::from("Production"),
            Self::Archived => String::from("Archived"),
        }
    }
}

impl Default for Mlstage {
    fn default() -> Mlstage {
        Self::None
    }
}




