use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelRegistrycreateWebhook200Response {
    #[serde(rename = "webhook", skip_serializing_if = "Option::is_none")]
    pub webhook: Option<Box<crate::models::MlRegistryWebhook>>,
}

impl ModelRegistrycreateWebhook200Response {
    pub fn new() -> ModelRegistrycreateWebhook200Response {
        ModelRegistrycreateWebhook200Response {
            webhook: None,
        }
    }
}


