use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Oauth2CreateCustomAppIntegration {
    /// indicates if an oauth client-secret should be generated 
    #[serde(rename = "confidential", skip_serializing_if = "Option::is_none")]
    pub confidential: Option<bool>,
    /// name of the custom oauth app 
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "redirect_urls")]
    pub redirect_urls: Vec<String>,
    #[serde(rename = "scopes", skip_serializing_if = "Option::is_none")]
    pub scopes: Option<Vec<String>>,
    /// Token access policy 
    #[serde(rename = "token_access_policy", skip_serializing_if = "Option::is_none")]
    pub token_access_policy: Option<Box<crate::models::Oauth2TokenAccessPolicy>>,
}

impl Oauth2CreateCustomAppIntegration {
    pub fn new(name: String, redirect_urls: Vec<String>) -> Oauth2CreateCustomAppIntegration {
        Oauth2CreateCustomAppIntegration {
            confidential: None,
            name,
            redirect_urls,
            scopes: None,
            token_access_policy: None,
        }
    }
}


