use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Oauth2UpdatePublishedAppIntegration {
    /// Token access policy to be updated in the published oauth app integration 
    #[serde(rename = "token_access_policy", skip_serializing_if = "Option::is_none")]
    pub token_access_policy: Option<Box<crate::models::Oauth2TokenAccessPolicy>>,
}

impl Oauth2UpdatePublishedAppIntegration {
    pub fn new() -> Oauth2UpdatePublishedAppIntegration {
        Oauth2UpdatePublishedAppIntegration {
            token_access_policy: None,
        }
    }
}


