use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PipelinesSerializedException {
    /// Runtime class of the exception
    #[serde(rename = "class_name", skip_serializing_if = "Option::is_none")]
    pub class_name: Option<String>,
    /// Exception message
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "stack", skip_serializing_if = "Option::is_none")]
    pub stack: Option<Vec<crate::models::PipelinesStackFrame>>,
}

impl PipelinesSerializedException {
    pub fn new() -> PipelinesSerializedException {
        PipelinesSerializedException {
            class_name: None,
            message: None,
            stack: None,
        }
    }
}


