use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProvisioningCreateVpcEndpointRequest {
    /// The ID of the VPC endpoint object in AWS.
    #[serde(rename = "aws_vpc_endpoint_id", skip_serializing_if = "Option::is_none")]
    pub aws_vpc_endpoint_id: Option<String>,
    #[serde(rename = "gcp_vpc_endpoint_info", skip_serializing_if = "Option::is_none")]
    pub gcp_vpc_endpoint_info: Option<Box<crate::models::ProvisioningGcpVpcEndpointInfo>>,
    /// The AWS region in which this VPC endpoint object exists.
    #[serde(rename = "region", skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    /// The human-readable name of the storage configuration.
    #[serde(rename = "vpc_endpoint_name")]
    pub vpc_endpoint_name: String,
}

impl ProvisioningCreateVpcEndpointRequest {
    pub fn new(vpc_endpoint_name: String) -> ProvisioningCreateVpcEndpointRequest {
        ProvisioningCreateVpcEndpointRequest {
            aws_vpc_endpoint_id: None,
            gcp_vpc_endpoint_info: None,
            region: None,
            vpc_endpoint_name,
        }
    }
}


