use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProvisioningAwsKeyInfo {
    /// The AWS KMS key alias.
    #[serde(rename = "key_alias", skip_serializing_if = "Option::is_none")]
    pub key_alias: Option<String>,
    /// The AWS KMS key's Amazon Resource Name (ARN).
    #[serde(rename = "key_arn")]
    pub key_arn: String,
    /// The AWS KMS key region.
    #[serde(rename = "key_region")]
    pub key_region: String,
    /// This field applies only if the `use_cases` property includes `STORAGE`. If this is set to `true` or omitted, the key is also used to encrypt cluster EBS volumes. If you do not want to use this key for encrypting EBS volumes, set to `false`.
    #[serde(rename = "reuse_key_for_cluster_volumes", skip_serializing_if = "Option::is_none")]
    pub reuse_key_for_cluster_volumes: Option<bool>,
}

impl ProvisioningAwsKeyInfo {
    pub fn new(key_arn: String, key_region: String) -> ProvisioningAwsKeyInfo {
        ProvisioningAwsKeyInfo {
            key_alias: None,
            key_arn,
            key_region,
            reuse_key_for_cluster_volumes: None,
        }
    }
}


