use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ProvisioningEndpointUseCase : This enumeration represents the type of Databricks VPC [endpoint service](https://Docsaws.amazon.com/vpc/latest/privatelink/endpoint-service.html) that was used when creating this VPC endpoint.

/// This enumeration represents the type of Databricks VPC [endpoint service](https://Docsaws.amazon.com/vpc/latest/privatelink/endpoint-service.html) that was used when creating this VPC endpoint.
#[derive(JsonSchema, Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProvisioningEndpointUseCase {
    #[serde(rename = "WORKSPACE_ACCESS")]
    WorkspaceAccess,
    #[serde(rename = "DATAPLANE_RELAY_ACCESS")]
    DataplaneRelayAccess,

}

impl ToString for ProvisioningEndpointUseCase {
    fn to_string(&self) -> String {
        match self {
            Self::WorkspaceAccess => String::from("WORKSPACE_ACCESS"),
            Self::DataplaneRelayAccess => String::from("DATAPLANE_RELAY_ACCESS"),
        }
    }
}

impl Default for ProvisioningEndpointUseCase {
    fn default() -> ProvisioningEndpointUseCase {
        Self::WorkspaceAccess
    }
}




