use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProvisioningStsRole {
    /// The external ID that needs to be trusted by the cross-account role. This is always your Databricks account ID.
    #[serde(rename = "external_id", skip_serializing_if = "Option::is_none")]
    pub external_id: Option<String>,
    /// The Amazon Resource Name (ARN) of the cross account role.
    #[serde(rename = "role_arn", skip_serializing_if = "Option::is_none")]
    pub role_arn: Option<String>,
}

impl ProvisioningStsRole {
    pub fn new() -> ProvisioningStsRole {
        ProvisioningStsRole {
            external_id: None,
            role_arn: None,
        }
    }
}


