use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ProvisioningCloudResourceContainer : The general workspace configurations that are specific to cloud providers.



#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProvisioningCloudResourceContainer {
    #[serde(rename = "gcp", skip_serializing_if = "Option::is_none")]
    pub gcp: Option<Box<crate::models::ProvisioningCustomerFacingGcpCloudResourceContainer>>,
}

impl ProvisioningCloudResourceContainer {
    /// The general workspace configurations that are specific to cloud providers.
    pub fn new() -> ProvisioningCloudResourceContainer {
        ProvisioningCloudResourceContainer {
            gcp: None,
        }
    }
}


