use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServingEndpointCoreConfigInput {
    #[serde(rename = "served_models")]
    pub served_models: Vec<crate::models::ServingServedModelInput>,
    /// The traffic config defining how invocations to the serving endpoint should be routed.
    #[serde(rename = "traffic_config", skip_serializing_if = "Option::is_none")]
    pub traffic_config: Option<Box<crate::models::ServingTrafficConfig>>,
}

impl ServingEndpointCoreConfigInput {
    pub fn new(served_models: Vec<crate::models::ServingServedModelInput>) -> ServingEndpointCoreConfigInput {
        ServingEndpointCoreConfigInput {
            served_models,
            traffic_config: None,
        }
    }
}


