use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SettingsIpAccessListInfo {
    /// Universally unique identifier (UUID) of the IP access list.
    #[serde(rename = "list_id", skip_serializing_if = "Option::is_none")]
    pub list_id: Option<String>,
    /// Total number of IP or CIDR values.
    #[serde(rename = "address_count", skip_serializing_if = "Option::is_none")]
    pub address_count: Option<i32>,
    /// Label for the IP access list. This **cannot** be empty.
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// Specifies whether this IP access list is enabled.
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// User ID of the user who created this list.
    #[serde(rename = "created_by", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<i64>,
    #[serde(rename = "list_type", skip_serializing_if = "Option::is_none")]
    pub list_type: Option<crate::models::SettingslistType>,
    /// Update timestamp in milliseconds.
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<i64>,
    #[serde(rename = "ip_addresses", skip_serializing_if = "Option::is_none")]
    pub ip_addresses: Option<Vec<String>>,
    /// Creation timestamp in milliseconds.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i64>,
    /// User ID of the user who updated this list.
    #[serde(rename = "updated_by", skip_serializing_if = "Option::is_none")]
    pub updated_by: Option<i64>,
}

impl SettingsIpAccessListInfo {
    pub fn new() -> SettingsIpAccessListInfo {
        SettingsIpAccessListInfo {
            list_id: None,
            address_count: None,
            label: None,
            enabled: None,
            created_by: None,
            list_type: None,
            updated_at: None,
            ip_addresses: None,
            created_at: None,
            updated_by: None,
        }
    }
}


