use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SharingCleanRoomCollaboratorInfo {
    /// The global Unity Catalog metastore id of the collaborator. Also known as the sharing identifier. The identifier is of format __cloud__:__region__:__metastore-uuid__. 
    #[serde(rename = "global_metastore_id", skip_serializing_if = "Option::is_none")]
    pub global_metastore_id: Option<String>,
    /// The organization name of the collaborator. This is configured in the metastore for Delta Sharing and is used to identify the organization to other collaborators. 
    #[serde(rename = "organization_name", skip_serializing_if = "Option::is_none")]
    pub organization_name: Option<String>,
}

impl SharingCleanRoomCollaboratorInfo {
    pub fn new() -> SharingCleanRoomCollaboratorInfo {
        SharingCleanRoomCollaboratorInfo {
            global_metastore_id: None,
            organization_name: None,
        }
    }
}


