use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SqlPermissionLevel : This describes an enum

/// This describes an enum
#[derive(JsonSchema, Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SqlPermissionLevel {
    #[serde(rename = "CAN_VIEW")]
    View,
    #[serde(rename = "CAN_RUN")]
    Run,
    #[serde(rename = "CAN_MANAGE")]
    Manage,

}

impl ToString for SqlPermissionLevel {
    fn to_string(&self) -> String {
        match self {
            Self::View => String::from("CAN_VIEW"),
            Self::Run => String::from("CAN_RUN"),
            Self::Manage => String::from("CAN_MANAGE"),
        }
    }
}

impl Default for SqlPermissionLevel {
    fn default() -> SqlPermissionLevel {
        Self::View
    }
}




