use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SqlListQueriesResponse {
    /// Whether there is another page of results.
    #[serde(rename = "has_next_page", skip_serializing_if = "Option::is_none")]
    pub has_next_page: Option<bool>,
    /// A token that can be used to get the next page of results.
    #[serde(rename = "next_page_token", skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
    #[serde(rename = "res", skip_serializing_if = "Option::is_none")]
    pub res: Option<Vec<crate::models::SqlQueryInfo>>,
}

impl SqlListQueriesResponse {
    pub fn new() -> SqlListQueriesResponse {
        SqlListQueriesResponse {
            has_next_page: None,
            next_page_token: None,
            res: None,
        }
    }
}


