use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SqlEditAlert {
    /// Name of the alert.
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "options")]
    pub options: Box<crate::models::SqlAlertOptions>,
    /// Query ID.
    #[serde(rename = "query_id")]
    pub query_id: String,
    /// Number of seconds after being triggered before the alert rearms itself and can be triggered again. If `null`, alert will never be triggered again.
    #[serde(rename = "rearm", skip_serializing_if = "Option::is_none")]
    pub rearm: Option<i32>,
}

impl SqlEditAlert {
    pub fn new(name: String, options: crate::models::SqlAlertOptions, query_id: String) -> SqlEditAlert {
        SqlEditAlert {
            name,
            options: Box::new(options),
            query_id,
            rearm: None,
        }
    }
}


