use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(JsonSchema, Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SqlRepeatedEndpointConfPairs {
    #[serde(rename = "config_pair", skip_serializing_if = "Option::is_none")]
    pub config_pair: Option<Vec<crate::models::SqlEndpointConfPair>>,
    #[serde(rename = "configuration_pairs", skip_serializing_if = "Option::is_none")]
    pub configuration_pairs: Option<Vec<crate::models::SqlEndpointConfPair>>,
}

impl SqlRepeatedEndpointConfPairs {
    pub fn new() -> SqlRepeatedEndpointConfPairs {
        SqlRepeatedEndpointConfPairs {
            config_pair: None,
            configuration_pairs: None,
        }
    }
}


