use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SqlobjectType : A singular noun object type.

/// A singular noun object type.
#[derive(JsonSchema, Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SqlobjectType {
    #[serde(rename = "alert")]
    Alert,
    #[serde(rename = "dashboard")]
    Dashboard,
    #[serde(rename = "data_source")]
    DataSource,
    #[serde(rename = "query")]
    Query,

}

impl ToString for SqlobjectType {
    fn to_string(&self) -> String {
        match self {
            Self::Alert => String::from("alert"),
            Self::Dashboard => String::from("dashboard"),
            Self::DataSource => String::from("data_source"),
            Self::Query => String::from("query"),
        }
    }
}

impl Default for SqlobjectType {
    fn default() -> SqlobjectType {
        Self::Alert
    }
}




