use schemars::JsonSchema;
/*
 * Databricks Accounts and Workspace REST API on ALL
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SqlobjectTypePlural : Always a plural of the object type.

/// Always a plural of the object type.
#[derive(JsonSchema, Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SqlobjectTypePlural {
    #[serde(rename = "alerts")]
    Alerts,
    #[serde(rename = "dashboards")]
    Dashboards,
    #[serde(rename = "data_sources")]
    DataSources,
    #[serde(rename = "queries")]
    Queries,

}

impl ToString for SqlobjectTypePlural {
    fn to_string(&self) -> String {
        match self {
            Self::Alerts => String::from("alerts"),
            Self::Dashboards => String::from("dashboards"),
            Self::DataSources => String::from("data_sources"),
            Self::Queries => String::from("queries"),
        }
    }
}

impl Default for SqlobjectTypePlural {
    fn default() -> SqlobjectTypePlural {
        Self::Alerts
    }
}




