---
apiVersion: com.dstancu.databricks/v1
kind: DatabricksSecretScope
metadata:
  name: my-secret-scope
  namespace: default
spec:
  scope:
    name: my-super-cool-scope
---
apiVersion: v1
data:
  hello: d3VybA==
  foo: YmFy
kind: Secret    
metadata:
  name: my-super-cool-secret
type: Opaque
---
apiVersion: com.dstancu.databricks/v1
kind: DatabricksSecret
metadata:
  name: my-super-cool-databricks-secret
  namespace: default
spec:
  scope: my-super-cool-scope
  secret_name: my-super-cool-secret