{{- $svcAccount := include "databricks-kube-operator.serviceAccountName" . }}
{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ $svcAccount }}"
  namespace: {{ .Release.Namespace }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
        - ""
        - apiextensions.k8s.io
        - com.dstancu.databricks
    resources:
        - configmaps
        - customresourcedefinitions
        - databricksjobs
        - databricksjobs/status
        - repos
        - gitcredentials
        - secrets
    verbs: ["get", "list", "watch"]
  - apiGroups:
        - ""
        - com.dstancu.databricks
    resources:
        - databricksjobs
        - databricksjobs/status
        - repos
        - gitcredentials
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
subjects:
- namespace: {{ .Release.Namespace }}
  kind: ServiceAccount
  name: "{{ $svcAccount }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}
