apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: databricks-kube-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "databricks-kube-operator.name" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: databricks-kube-operator
  replicas: 1
  serviceName: databricks-kube-operator
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        app: {{ template "databricks-kube-operator.name" . }}
    spec:
      serviceAccountName: databricks-kube-operator
      terminationGracePeriodSeconds: 10
      containers:
      - name: dko
        image: {{ .Values.image.repository }}:{{default .Chart.AppVersion .Values.image.tag }}
        imagePullPolicy: Always
        env:
          - name: DATABRICKS_KUBE_CONFIGMAP
            value: {{ .Values.configMapName }}
          - name: RUST_LOG
            value: databricks_kube
        resources:
          {{- toYaml .Values.resources | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
