apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: databricks-kube-operator
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: databricks-kube-operator
  replicas: 1
  serviceName: databricks-kube-operator
  template:
    metadata:
      labels:
        app: databricks-kube-operator
    spec:
      serviceAccountName: databricks-kube-operator
      terminationGracePeriodSeconds: 10
      containers:
      - name: dko
        image: ghcr.io/mach-kernel/databricks-kube-operator:0.3.3
        imagePullPolicy: Always
        env:
          - name: DATABRICKS_KUBE_CONFIGMAP
            value: {{ .Values.configMapName }}
          - name: RUST_LOG
            value: databricks_kube
